### ISSUE TITLE
Front Page Banner (Slides) not working

### ISSUE THREAD

**Issue by babuprasads** [dasistwas/moodle-theme_squared#1]
Hi
1. I have selected 4 slide show for the front page, but the slider does not seem to work. I have not touched any code.
2. Also how do you configure the SQUARES on the Slide banner on front page. It says it can be set in the theme setting page, but do not see any options. I was able to edit (blank out) the text but not configure the hyperlinks or change images on it.

![frontpagebanner](https://cloud.githubusercontent.com/assets/10516467/5722007/37f11780-9b5e-11e4-9162-8fd1628b0810.png)

**Comment by dasistwas** [comment]
Hi,

where did you put the images? What moodle version are you using? Indeed, there is a problem with the images in the slideshow. I will have a look at that. Does it work with 3 or 2 images?

**Comment by dasistwas** [comment]
Did the slideshow work before you modified anything?

**Comment by babuprasads** [comment]
Hi

I am using Moodle 2.7.2. The slideshow was not working earlier too. So changed the images, and refreshed the server.

The Images are uploaded under \pix

I tried with all options of 2, 3, 4 and 5 images. The size of the images were maintained as the original ones with the same file names.

Regards

Babu

Sent from Windows Mail

From: David Bogner
Sent: ‎Tuesday‎, ‎13‎ ‎January‎ ‎2015 ‎20‎:‎41
To: dasistwas/moodle-theme_squared
Cc: Babu Prasad

Did the slideshow work before you modified anything?

**Comment by dasistwas** [comment]
Hi,

I uploaded a new version, that fixes the slideshow issue. If you still encounter problems, it might not be related to the theme. Do not upload images in the theme folder, use the theme settings page for that:
To configure the slideshow use that link on your moodle site: /admin/settings.php?section=theme_squared_slideshow

Best,
David

**Comment by babuprasads** [comment]
Hi David

Sorry to bother you, not sure if I am missing anything here - did not find the ‘uninstall’ option in the plugin section, so had to delete the folder and install the updated plugin again.

Post that no change, I have updated the slides from the theme settings.

Second - you have mentioned “To configure the slideshow use that link on your moodle site: /admin/settings.php?section=theme_squared_slideshow”, can you help me with the steps, hope I am not asking for too much details.

NOTE: THE THEME IS AWESOME, thank you for the upload.

Regards

Babu

Sent from Windows Mail

From: David Bogner
Sent: ‎Wednesday‎, ‎14‎ ‎January‎ ‎2015 ‎22‎:‎40
To: dasistwas/moodle-theme_squared
Cc: Babu Prasad

Hi,

I uploaded a new version, that fixes the slideshow issue. If you still encounter problems, it might not be related to the theme. Do not upload images in the theme folder, use the theme settings page for that:
To configure the slideshow use that link on your moodle site: /admin/settings.php?section=theme_squared_slideshow

Best,
David

**Comment by dasistwas** [comment]
Hi,

please have a look at https://docs.moodle.org/27/en/Standard_themes customizing the squared theme works similar to customizing the more-theme which is explained in the link above.

Best
David
