### ISSUE TITLE
Replace google+ link and icon with instagram in general settings of the theme

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-theme_squared#5]
We need to replace our google+ account with instagram account. Therefore we would need to replace google+ link with instagram link in the general theme settings. Also icon should be replaced.
And there is a little bug: A line is drawn through all the icons. This line should be removed.

**Comment by gjb2048** [comment]
Hi David,

Will do.

Gareth

**Comment by gjb2048** [comment]
Note: In footer settings.

**Comment by gjb2048** [comment]
Must be 29px by 29px -> https://en.instagram-brand.com/assets/icons

**Comment by gjb2048** [comment]
Hi David,

Done.  I've had to alter the size and padding because of Instagram's mandatory guidelines.

Gareth

**Comment by dasistwas** [comment]
Hi Gareth,

great work thank you! Looks really good. One thing left to do: When the link is left empty in the settings, could you also remove the specific icon from the footer?

Kind regards,
David

**Comment by gjb2048** [comment]
Hi David,

That's odd, but will do.

G

**Comment by gjb2048** [comment]
Hi David,

Done.  There was old code that I've removed and old new code that I've fixed.

Kind regards,

Gareth

**Comment by dasistwas** [comment]
Thank you! Great work as usual.
