### ISSUE TITLE
Course management area: Checkboxes disappear on hover

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-theme_squared#7]
Hi @gjb2048 

there is an issue in squared course managment. See attached video. Could you fix this?

Kind regards,
David

https://user-images.githubusercontent.com/1620975/117401792-7fdfc200-af05-11eb-8ede-721ec9e36a1d.mp4

**Comment by gjb2048** [comment]
@dasistwas Will investigate.

**Comment by gjb2048** [comment]
@dasistwas Fixed I hope!  Please update and do a 'purge all caches'.

**Comment by gjb2048** [comment]
@dasistwas Are you happy with the fix?

**Comment by dasistwas** [comment]
Hi Gareth,

yes it works perfect!

Thank you!
